# Component Info
info:
 component: cloud_config-server
 
# HTTP Server
server:
 port: 8888
 
spring:
 # Spring Cloud Config Server Repository
 cloud:
  config:
   server:
    git:
     uri: https://github.com/leninceiba/springCloudConfigServer
     skipSslValidation: true
     username: leninceiba
     password: lGr146327.
 
 # Spring properties 
 profiles: 
  active: dev
  
logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'    