#Component Info
info:
 component: spring-cloud-netflix-zuul
 
#Spring Application Name 
spring:
 application:
  name: spring-cloud-netflix-zuul
 
#Server Port
server:
 port: 8765 
 
#Endpoints 
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  sensitive: false
 
#Zuul routes active 
zuul: 
 routes:
  public-restservice: 
   path: /public/**
   serviceId: public-restservice
 
#Eureka Instance ID
eureka:
 instance:
  instanceId: ${spring.application.name}:${server.port} 
 
#Ribbon Activation
ribbon:
 eureka:
  enabled: true